using Uno.UI.Hosting;

namespace RichTextBox.IntegrationTestHost;

// Skia desktop entry point only. The WinUI 3 head excludes this file (see the
// csproj) and uses the entry point generated by the WinAppSDK XAML compiler.
public static class Program
{
    [STAThread]
    public static async Task Main(string[] args)
    {
        var host = UnoPlatformHostBuilder.Create()
            .App(() => new App())
            .UseX11()
            .UseMacOS()
            .UseWin32()
            .Build();
        await host.RunAsync();
    }
}
