namespace System.Windows;

public enum BaseValueSourceInternal
{
    Unknown = 0,
    Default = 1,
    Inherited = 2,
    Local = 3,
}

// System.Windows.DependencyProperty class removed — use Microsoft.UI.Xaml.DependencyProperty
// (the global using alias 'DependencyProperty' resolves to it). WPF-specific extensions
// (AddOwner, OverrideMetadata) are provided as extension methods in WinUIDependencyPropertyExtensions.cs.

// WPF delegate signatures kept for source compatibility with linked WPF code.
public delegate void PropertyChangedCallback(DependencyObject d, DependencyPropertyChangedEventArgs e);
public delegate object CoerceValueCallback(DependencyObject d, object baseValue);
public delegate bool ValidateValueCallback(object value);

public readonly struct DependencyPropertyChangedEventArgs
{
    public DependencyProperty? Property { get; init; }
    public object? OldValue { get; init; }
    public object? NewValue { get; init; }
    public Entry NewEntry { get; init; }
    public BaseValueSourceInternal OldValueSource { get; init; }

    public static implicit operator DependencyPropertyChangedEventArgs(
        Microsoft.UI.Xaml.DependencyPropertyChangedEventArgs e)
        => new DependencyPropertyChangedEventArgs
        {
            Property = e.Property,
            OldValue = e.OldValue,
            NewValue = e.NewValue,
            OldValueSource = BaseValueSourceInternal.Local,
        };
}

public readonly struct Entry
{
    public bool IsDeferredReference { get; init; }
}

[System.Flags]
public enum FrameworkPropertyMetadataOptions
{
    None = 0,
    AffectsRender = 1,
    AffectsMeasure = 2,
    AffectsParentMeasure = 4,
    BindsTwoWayByDefault = 8,
    Inherits = 16,
    AffectsArrange = 0x20,
    AffectsParentArrange = 0x40,
    SubPropertiesDoNotAffectRender = 0x80,
    // Uno Platform-specific flags generated by DependencyObjectGenerator — kept for compatibility.
    ValueDoesNotInheritDataContext = 0x100,
    WeakStorage = 0x200,
}

public readonly struct ValueSource
{
    public BaseValueSource BaseValueSource { get; init; }
    public bool IsExpression { get; init; }
}

public enum BaseValueSource
{
    Local = 0,
    Inherited = 1,
}

public static class DependencyPropertyHelper
{
    public static ValueSource GetValueSource(DependencyObject obj, Microsoft.UI.Xaml.DependencyProperty dp) => new() { BaseValueSource = BaseValueSource.Local, IsExpression = false };
}
