namespace System.Windows;

public enum BaseValueSourceInternal
{
    Unknown = 0,
    Default = 1,
    Inherited = 2,
    Local = 3,
}

// System.Windows.DependencyProperty class removed — use Microsoft.UI.Xaml.DependencyProperty
// (the global using alias 'DependencyProperty' resolves to it). WPF-specific extensions
// (AddOwner, OverrideMetadata) are provided as extension methods in WinUIDependencyPropertyExtensions.cs.

// WPF delegate signatures kept for source compatibility with linked WPF code.
public delegate void PropertyChangedCallback(DependencyObject d, DependencyPropertyChangedEventArgs e);
public delegate object CoerceValueCallback(DependencyObject d, object baseValue);
public delegate bool ValidateValueCallback(object value);

public readonly struct DependencyPropertyChangedEventArgs
{
    public DependencyProperty? Property { get; init; }
    public object? OldValue { get; init; }
    public object? NewValue { get; init; }
    public Entry NewEntry { get; init; }
    public BaseValueSourceInternal OldValueSource { get; init; }

    public DependencyPropertyChangedEventArgs(DependencyProperty property, object? oldValue, object? newValue)
    {
        Property = property;
        OldValue = oldValue;
        NewValue = newValue;
        OldValueSource = BaseValueSourceInternal.Local;
        NewEntry = default;
    }

    public static implicit operator DependencyPropertyChangedEventArgs(
        Microsoft.UI.Xaml.DependencyPropertyChangedEventArgs e)
        => new DependencyPropertyChangedEventArgs
        {
            Property = e.Property,
            OldValue = e.OldValue,
            NewValue = e.NewValue,
            OldValueSource = BaseValueSourceInternal.Local,
        };
}

public readonly struct Entry
{
    public bool IsDeferredReference { get; init; }
}

[System.Flags]
public enum FrameworkPropertyMetadataOptions
{
    None = 0,
    AffectsRender = 1,
    AffectsMeasure = 2,
    AffectsParentMeasure = 4,
    BindsTwoWayByDefault = 8,
    Inherits = 16,
    AffectsArrange = 0x20,
    AffectsParentArrange = 0x40,
    SubPropertiesDoNotAffectRender = 0x80,
    Journal = 0x400,
    // Uno Platform-specific flags generated by DependencyObjectGenerator — kept for compatibility.
    ValueDoesNotInheritDataContext = 0x100,
    WeakStorage = 0x200,
}

public readonly struct ValueSource
{
    public BaseValueSource BaseValueSource { get; init; }
    public bool IsExpression { get; init; }
}

// Mirrors the member order/values of WPF System.Windows.BaseValueSource so the
// precedence comparisons in linked DataGrid code (e.g. GetCoercedTransferProperty-
// Value) are meaningful. The Uno bridge only ever reports Default or Local — it
// cannot observe styles/inheritance — but the full set keeps the type faithful.
public enum BaseValueSource
{
    Unknown = 0,
    Default = 1,
    Inherited = 2,
    DefaultStyle = 3,
    DefaultStyleTrigger = 4,
    Style = 5,
    TemplateTrigger = 6,
    StyleTrigger = 7,
    ImplicitStyleReference = 8,
    ParentTemplate = 9,
    ParentTemplateTrigger = 10,
    Local = 11,
}

public static class DependencyPropertyHelper
{
    // Distinguish a locally-set value from the default, the only precedence
    // levels the Uno bridge can observe (via ReadLocalValue). Styles and
    // inheritance are reported as Default.
    public static ValueSource GetValueSource(DependencyObject obj, Microsoft.UI.Xaml.DependencyProperty dp)
        => new()
        {
            BaseValueSource = obj.ReadLocalValue(dp) == Microsoft.UI.Xaml.DependencyProperty.UnsetValue
                ? BaseValueSource.Default
                : BaseValueSource.Local,
            IsExpression = false,
        };
}
